# Generated by Django 5.1.4 on 2025-01-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_book_author_remove_book_genre_book_authors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
