# Generated by Django 5.1.4 on 2025-01-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_book_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author',
            field=models.BooleanField(default=True),
        ),
    ]
